export declare const commonBgBasic: string;
export declare const commonBgElevation: string;
export declare const commonBgDeep: string;
export declare const commonBgDeeper: string;
export declare const commonBgStrong: string;
export declare const commonBgStronger: string;
export declare const commonBgInverse: string;
export declare const commonBgPrimary: string;
export declare const commonBgSecondary: string;
export declare const commonBgDim: string;
export declare const commonBgBlack: string;
export declare const commonTextBasic: string;
export declare const commonTextLight: string;
export declare const commonTextLighter: string;
export declare const commonTextBright: string;
export declare const commonTextInverse: string;
export declare const commonTextPrimary: string;
export declare const commonTextPrimaryLight: string;
export declare const commonTextPrimaryExtreme: string;
export declare const commonTextSecondary: string;
export declare const commonTextSecondaryLight: string;
export declare const commonTextSecondaryExtreme: string;
export declare const commonTextConfirmed: string;
export declare const commonTextWarningMinor: string;
export declare const commonTextWarningMajor: string;
export declare const commonTextError: string;
export declare const commonTextDone: string;
export declare const commonTextColorA: string;
export declare const commonTextColorB: string;
export declare const commonTextColorC: string;
export declare const commonTextColorD: string;
export declare const commonBorderBasic: string;
export declare const commonBorderLight: string;
export declare const commonBorderBright: string;
export declare const commonBorderStrong: string;
export declare const commonBorderStronger: string;
export declare const commonBorderExtreme: string;
export declare const commonBorderInverse: string;
export declare const commonBorderPrimary: string;
export declare const commonBorderSecondary: string;
export declare const commonBorderConfirmed: string;
export declare const commonBorderWarningMinor: string;
export declare const commonBorderWarningMajor: string;
export declare const commonBorderError: string;
export declare const controlLinedBgBasic: string;
export declare const controlLinedBgBasicHover: string;
export declare const controlLinedBgBasicActive: string;
export declare const controlLinedBgPrimary: string;
export declare const controlLinedBgPrimaryHover: string;
export declare const controlLinedBgPrimaryActive: string;
export declare const controlLinedBorderBasicHover: string;
export declare const controlLinedBorderBasicActive: string;
export declare const controlLinedBorderPrimaryHover: string;
export declare const controlLinedBorderPrimaryActive: string;
export declare const controlFilledBgInverse: string;
export declare const controlFilledBgInverseHover: string;
export declare const controlFilledBgInverseActive: string;
export declare const controlFilledBgPrimary: string;
export declare const controlFilledBgPrimaryHover: string;
export declare const controlFilledBgPrimaryActive: string;
export declare const controlFilledBgBasic: string;
export declare const controlFilledBgBasicActive: string;
export declare const controlFilledBgInversePrimaryHover: string;
export declare const controlFilledBgInversePrimaryActive: string;
export declare const inputBgDisabled: string;
export declare const inputBorderFocus: string;
export declare const tableBgHeader: string;
export declare const tableBgCellBasic: string;
export declare const tableBgCellOdd: string;
export declare const tableBgCellSelected: string;
export declare const tableBgCellHover: string;
export declare const tableBgCellTotal: string;
export declare const tableBgCellSubTotal: string;
export declare const tableBgCellEditing: string;
export declare const tableBgCellUpperDepth: string;
export declare const tableBgCellEditable: string;
export declare const tableBorderHeader: string;
export declare const tableBorderCell: string;
export declare const tableBorderCellFocus: string;
export declare const tableBorderCellEditing: string;
export declare const navLeftBg1LevelHover: string;
export declare const navLeftBgLastChildSelected: string;
export declare const navLeftBg3Level: string;
export declare const navLeftTextLastChildSelected: string;
export declare const navLeftTextSelected: string;
export declare const navTopBgBasic: string;
export declare const navTopBgSwitch: string;
export declare const navTopBgSwitchHolder: string;
export declare const navTopBorderSelected: string;
export declare const navTopTextSysNameBasic: string;
export declare const navTopTextSysNamePrimary: string;
export declare const infoBgPrimary: string;
export declare const infoBgSecondary: string;
export declare const infoBgConfirmed: string;
export declare const infoBgWarningMinor: string;
export declare const infoBgWarningMajor: string;
export declare const infoBgError: string;
export declare const infoBgDone: string;
export declare const infoBgColorA: string;
export declare const infoBgColorB: string;
export declare const infoBgColorC: string;
export declare const infoBgColorD: string;
export declare const infoBorderPrimary: string;
export declare const infoBorderSecondary: string;
export declare const infoBorderConfirmed: string;
export declare const infoBorderWarningMinor: string;
export declare const infoBorderWarningMajor: string;
export declare const infoBorderError: string;
export declare const infoBorderDone: string;
export declare const infoBorderColorA: string;
export declare const infoBorderColorB: string;
export declare const infoBorderColorC: string;
export declare const infoBorderColorD: string;
export declare const infoTextPrimary: string;
export declare const infoTextSecondary: string;
export declare const infoTextConfirmed: string;
export declare const infoTextWarningMinor: string;
export declare const infoTextWarningMajor: string;
export declare const infoTextError: string;
export declare const infoTextDone: string;
export declare const infoTextColorA: string;
export declare const infoTextColorB: string;
export declare const infoTextColorC: string;
export declare const infoTextColorD: string;
export declare const legendBasicBgColorALight = "#D8D9F9";
export declare const legendBasicBgColorANormal = "#B4B5F3";
export declare const legendBasicBgColorAStrong = "#5E5FB7";
export declare const legendBasicBgColorBLight = "#E3F0FF";
export declare const legendBasicBgColorBNormal = "#ADCEFF";
export declare const legendBasicBgColorBStrong = "#77A5FF";
export declare const legendBasicBgColorCLight = "#DAF088";
export declare const legendBasicBgColorCNormal = "#C4E167";
export declare const legendBasicBgColorCStrong = "#89B129";
export declare const legendBasicBgColorDLight = "#FDD4DA";
export declare const legendBasicBgColorDNormal = "#FCA9BF";
export declare const legendBasicBgColorDStrong = "#E12991";
export declare const legendBasicBorderColorAStrong = "#5E5FB7";
export declare const legendBasicBorderColorAExtreme = "#303188";
export declare const legendBasicBorderColorBStrong = "#77A5FF";
export declare const legendBasicBorderColorBExtreme = "#567FDB";
export declare const legendBasicBorderColorCStrong = "#89B129";
export declare const legendBasicBorderColorCExtreme = "#41620A";
export declare const legendBasicBorderColorDStrong = "#E12991";
export declare const legendBasicBorderColorDExtreme = "#820D72";
export declare const legendStatusBgConfirmedBright = "#DCFBEA";
export declare const legendStatusBgConfirmedLight = "#56D8AA";
export declare const legendStatusBgConfirmedNormal = "#00806A";
export declare const legendStatusBgWarningMinorBright = "#FFF8CD";
export declare const legendStatusBgWarningMinorLight = "#FFE56A";
export declare const legendStatusBgWarningMinorNormal = "#FFC907";
export declare const legendStatusBgWarningMajorBright = "#FEEFD6";
export declare const legendStatusBgWarningMajorLight = "#FFCB7A";
export declare const legendStatusBgWarningMajorNormal = "#FF9322";
export declare const legendStatusBgErrorBright = "#FEE6DB";
export declare const legendStatusBgErrorLight = "#FDA293";
export declare const legendStatusBgErrorNormal = "#F94B50";
export declare const legendStatusBgDoneBright = "#F1F4F3";
export declare const legendStatusBgDoneLight = "#DDE0DF";
export declare const legendStatusBgDoneNormal = "#979998";
export declare const legendStatusBorderColorConfirmedNormal = "#00806A";
export declare const legendStatusBorderColorConfirmedStrong = "#01463A";
export declare const legendStatusBorderColorConfirmedExtreme = "#052923";
export declare const legendStatusBorderColorWarningMinorNormal = "#FFC907";
export declare const legendStatusBorderColorWarningMinorStrong = "#B78803";
export declare const legendStatusBorderColorWarningMinorExtreme = "#7A5501";
export declare const legendStatusBorderColorWarningMajorNormal = "#FF9322";
export declare const legendStatusBorderColorWarningMajorStrong = "#B75511";
export declare const legendStatusBorderColorWarningMajorExtreme = "#7A2B06";
export declare const legendStatusBorderColorErrorNormal = "#F94B50";
export declare const legendStatusBorderColorErrorStrong = "#B32542";
export declare const legendStatusBorderColorErrorExtreme = "#770E36";
export declare const legendStatusBorderColorDoneNormal = "#979998";
export declare const legendStatusBorderColorDoneStrong = "#5B5C5B";
export declare const legendStatusBorderColorDoneExtreme = "#1F1F1F";
export declare const imageLinkBgA = "#2D9BB2";
export declare const imageLinkBgB = "#0B3E63";
export declare const imageLinkBgC = "#01463A";
export declare const imageLinkBgD = "#140D48";
export declare const imageLinkBgE = "#FFF8CD";
export declare const imageLinkBgF = "#B4FAEF";
export declare const imageLinkBgG = "#EEEAF8";
export declare const imageLinkBgH = "#E3F0FF";
export declare const requiredRed = "#F94B50";
